// https://github.com/t32k/stylestats/blob/master/assets/default.json

module.exports = {
	"config": {
		"published": false,
		"paths": false,
		"stylesheets": false,
		"styleElements": false,
		"size": true,
		"dataUriSize": true,
		"ratioOfDataUriSize": false,
		"gzippedSize": true,
		"simplicity": true,
		"rules": true,
		"selectors": true,
		"declarations": true,
		"averageOfIdentifier": true,
		"mostIdentifier": true,
		"mostIdentifierSelector": true,
		"averageOfCohesion": true,
		"lowestCohesion": true,
		"lowestCohesionSelector": true,
		"totalUniqueFontSizes": true,
		"uniqueFontSizes": true,
		"totalUniqueFontFamilies": true,
		"uniqueFontFamilies": true,
		"totalUniqueColors": true,
		"uniqueColors": true,
		"totalUniqueBackgroundImages": true,
		"uniqueBackgroundImages": true,
		"idSelectors": true,
		"universalSelectors": true,
		"unqualifiedAttributeSelectors": true,
		"javascriptSpecificSelectors": "[#\\.]js\\-",
		"userSpecifiedSelectors": false,
		"importantKeywords": false,
		"floatProperties": false,
		"mediaQueries": true,
		"propertiesCount": 0,
		"requestOptions": {}
	},
	"outfile": true,
	"type": "json"
}
